name = "peekly"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "peekly"
database_id = "b4123e02-0514-4b4f-88b5-49522252d3c5"

[triggers]
crons = ["0 9 * * 1"]

[vars]
APP_NAME = "Peekly"
