name = "whoshere"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "whoshere"
database_id = "local"

[vars]
APP_NAME = "Whoshere"
